name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies (Ubuntu)
        run: sudo apt-get update && sudo apt-get install -y libnss3 libatk1.0-0 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxrandr2 libgbm-dev libasound2 libpango1.0-0

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Chromium
        run: npx playwright install --with-deps chromium

      - name: Run Playwright Tests (Headful Mode with Debugging)
        env:
          SIGN_IN: ${{ secrets.SIGN_IN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: npx playwright test --headed --trace on --timeout=60000 --workers=1

      - name: Upload Playwright Trace
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-trace
          path: test-results/**/*.zip

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
