name: Playwright Tests

on:
  push:            # Trigger tests when code is pushed to the repo
    branches:
      - main       # Specify which branch to watch (e.g., "main")
  pull_request:    # Trigger tests for pull requests
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Use a Linux environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Specify Node.js version

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run Playwright Tests
        env:
          SIGN_IN: ${{ secrets.SIGN_IN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: npx playwright test tests/test.spec.js

      - name: Upload Playwright Report
        if: always() # Always upload reports, even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report # Upload Playwright's HTML report
